### ISSUE TITLE
openLimitedPhotoLibraryPicker result promise should get resolved when the picker is closed only

### ISSUE THREAD

**Issue by mtnt** [zoontek/react-native-permissions#743] opened 2023-01-11 14:19 UTC
### Why it is needed?

There is no way to determine when allowed photos list has changed.

### Code sample

```js
await openLimitedPhotoLibraryPicker();

Cameraroll.getPhotos(...)
```

**Comment by zoontek** [comment] 2023-01-12 11:28
Duplicate of https://github.com/zoontek/react-native-permissions/issues/689

**Closed as completed** 2023-01-12 11:28 UTC
Labels: duplicate
