### ISSUE TITLE
Unable to resolve dependency tree

### ISSUE THREAD

**Issue by eresid** [zoontek/react-native-permissions#579] opened 2021-03-24 11:58 UTC
# Bug report

## Summary

<img width="695" alt="Screenshot 2021-03-24 at 13 54 55" src="https://user-images.githubusercontent.com/3881790/112306491-86451200-8ca8-11eb-8a3a-f01736a1d51e.png">

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 179.39 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
    Yarn: Not Found
    npm: 7.5.4 - ~/.nvm/versions/node/v12.20.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.9.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 0.63.4

## Steps to reproduce

1. npm install react-native-permissions
2. npm i

**Comment by zoontek** [comment] 2021-03-24 14:15
Which version of `npm` are you using? If you are using npm v7, try install deps with `--legacy-peer-deps`

**Comment by mikatzou** [comment] 2021-03-24 18:01
I'm hitting a very similar issue as well. Unfortunately, using --legacy-peer-deps didn't work either.

`npm install --save --legact-peer-deps
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: BarebonesCoreTestApp@0.0.1
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@">=16.13.1" from react-native-permissions@3.0.1
npm ERR!   node_modules/react-native-permissions
npm ERR!     react-native-permissions@"^3.0.0" from the root project
npm ERR!   1 more (react-native)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.1" from react-native-windows@0.64.1
npm ERR! node_modules/react-native-windows
npm ERR!   peer react-native-windows@">=0.62.0" from react-native-permissions@3.0.1
npm ERR!   node_modules/react-native-permissions
npm ERR!     react-native-permissions@"^3.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

`System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
    Memory: 18.08 GB / 31.63 GB
  Binaries:
    Node: 15.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.0.15 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 26, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.14393.0, 10.0.16299.0, 10.0.17134.0, 10.0.17763.0, 10.0.18362.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    Visual Studio: 15.9.28307.1300 (Visual Studio Enterprise 2017), 16.8.31005.135 (Visual Studio Enterprise 2019)
  Languages:
    Java: 1.8.0_275
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

**Comment by zoontek** [comment] 2021-03-25 07:52
Confirmed, it seems linked: https://stackoverflow.com/questions/64573177/unable-to-resolve-dependency-tree-error-when-installing-npm-packages

I will try fo find what it is now recommended (dropping `peerDependencies` usage entirely?)

**Comment by mikehardy** [comment] 2021-03-25 14:15
I was really curious about this so I read that stackoverflow (good link @zoontek thanks)

peerDependencies still seems valid, but people have gotten lazy keeping them correct because npm was always ignoring them - both on the maintainer side not really keeping the ranges correct and the consumer side not really keeping things up to date.

Looks like npm7 is going to change the world there, everyone needs to get a lot more proactive

To the OP: this package depends on react-native-windows at >= 0.62 which could use react v16 (what you appear to have, based on the image you actually posted) but you installed react-native-windows at 0.64+ (based on the actually posted image) and that depends on react v17, so either upgrade your react to v17 to solve the tangle or tell npm to use "legacy-peer-deps" (aka, my peer dependencies are broken and I don't want to fix them so please ignore them like you used to)

The problem appears to be your project has incompatible react-native-windows and react versions, and npm is just enforcing that now with npm v7

I don't think it's a problem with react-native-permissions, as the peerDependencies here are all easy to satisfy ranges:

https://github.com/zoontek/react-native-permissions/blob/22588a076bb440e94aac6941b6b59cfa5763b586/package.json#L62-L66

**Comment by zoontek** [comment] 2021-04-01 14:49
Just take more time to check if it's an issue with the package, and @mikehardy seems right here.
I think we can close this issue for now.

**Closed as completed** 2021-04-01 14:50 UTC

**Comment by ankitbaid11326** [comment] 2021-04-04 07:04
This is happening with node 14. With node 12 its able to install

**Comment by mikehardy** [comment] 2021-04-04 15:05
@ankitbaid11326 there is no such thing as npm 14.

There is a node 14. There is an npm 7. npm 7 exhibits the issue (as noted above) but if I understand correctly you can if you like update npm 6 which came during the npm12 (and npm14!) era to npm 7 in those node installations.

So be careful, and do not confuse different tools and different versions, or you will have confused results
