### ISSUE TITLE
PERMISSIONS.IOS.LOCATION_WHEN_IN_USE always returns "Unavailable"

### ISSUE THREAD

**Issue by Yandamuri** [zoontek/react-native-permissions#604] opened 2021-05-13 15:48 UTC
# Bug report

## Summary

I am using location services in my app and I just need location services when only using app. So I used  `PERMISSIONS.IOS.LOCATION_WHEN_IN_USE` to request permission. But it returns "Unavailable".

## Environment info

"react-native": "0.63.2",
"react-native-permissions": "3.0.3"

Should we use `PERMISSIONS.IOS.LOCATION_ALWAYS` even though we use location services when only app is using?

**Comment by zoontek** [comment] 2021-05-14 07:50
@Yandamuri No. Add more details please, or I will close this issue.
PS: Clean your build, it's very often the cause of the problem.

**Comment by Yandamuri** [comment] 2021-05-14 08:58
@zoontek I have deleted app and clean build and then ran app. But still no change

This is how checked permission,
       
        let permissionStatus = await check("PERMISSIONS.IOS.LOCATION_WHEN_IN_USE");
        console.log('check permissions result', permissionStatus);  => 'check permissions result – "unavailable"'

This is what I have added in `info.plist`

        <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>Location Services are used to capture your location when you check-in and check-out your attendance.</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>Location Services are used to capture your location when you check-in and check-out your attendance.</string>
	<key>NSLocationUsageDescription</key>
	<string>Location Services are used to capture your location when you check-in and check-out your attendance.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Location Services are used to capture your location when you check-in and check-out your attendance.</string>

I checked in iPhone 6(iOS 12) and in iPhone SE(iOS 14.4.2). In both phones it's showing permission status as "Unavailable"

    OS: macOS 11.2.2
    CPU: (8) x64 Apple M1
    Memory: 94.77 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2

**Comment by zoontek** [comment] 2021-05-14 09:01
`NSLocationUsageDescription` is deprecated.
Did you delete the Xcode `DerivedData` too?

**Comment by Yandamuri** [comment] 2021-05-14 09:18
@zoontek NSLocationUsageDescription has been removed from `info.plist`. I have deleted Xcode DerivedData and clean build and then ran the app. Still no change.

**Comment by zoontek** [comment] 2021-05-14 09:20
- Did you forget to run a `pod install` after setting the `Permission-LocationWhenInUse` pod in your podfile? https://github.com/zoontek/react-native-permissions#ios
- Are Location services enabled on your device?

![1E05936D-FC5C-450D-8ED1-64C4412C77F8](https://user-images.githubusercontent.com/1902323/118250073-5e06b200-b4a6-11eb-985a-4f433dcee00b.jpeg)

If they are, please create a repository with the minimal amount of code to reproduce the issue.

**Comment by Yandamuri** [comment] 2021-05-14 09:58
@zoontek  I realized that I forgot to do the pod install. after that everything is fine. Thank you so much for your patience and prompt response. 

when I request for 'While using app". As soon as I gave "Allow" got another request to access location "Always". Is it natural behaviour of iOS?

**Comment by zoontek** [comment] 2021-05-14 09:59
> @zoontek I realized that I forgot to do the pod install. after that everything is fine. Thank you so much for your patience and prompt response.
> 
> when I request for 'While using app". As soon as I gave "Allow" got another request to access location "Always". Is it natural behaviour of iOS?

Yes. Continue to read the documentation, it's explained.

**Closed as completed by zoontek** 2021-05-14 09:59 UTC
