### ISSUE TITLE
Requesting bluetooth permissions causes API MISUSE error on iOS 12

### ISSUE THREAD

**Issue by kenvunz** [zoontek/react-native-permissions#464] opened 2020-05-19 08:26 UTC
# Bug report

## Summary
Only happens on iOS 12. Tested on real device running iOS 12.4.6

Calling `request(PERMISSIONS.IOS.BLUETOOTH_PERIPHERAL)` response with `RESULTS.DENIED` and an error in Xcode console `API MISUSE: <CBPeripheralManager: 0x2812a2ca0> can only accept this command while in the powered on state`.

This is probably the same issue as #264 but for version 2 branch. Let me know if you want me to report in the #264 instead.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 543.89 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.npm-packages/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

Library version: 2.1.4

## Steps to reproduce

1. Request `PERMISSIONS.IOS.BLUETOOTH_PERIPHERAL`

Describe what you expected to happen:

1. Should response without the error

**Comment by zoontek** [comment] 2020-05-19 08:36
Hello. This is probably more a duplicate of https://github.com/react-native-community/react-native-permissions/issues/458. Did you tried to request `BLUETOOTH_PERIPHERAL` permission without the `bluetooth-peripheral` background capability unchecked?

Edit: nevermind, I understand what you mean. I'm working on a fix.

**Comment by zoontek** [comment] 2020-05-21 16:21
Please try latest version: https://github.com/react-native-community/react-native-permissions/releases/tag/2.1.5

**Closed as completed by zoontek** 2020-05-21 16:21 UTC

**Comment by kenvunz** [comment] 2020-05-21 20:49
works great, no more error thrown!
