### ISSUE TITLE
Android check(POST_NOTIFICATIONS) never return blocked status

### ISSUE THREAD

**Issue by retyui** [zoontek/react-native-permissions#739] opened 2022-12-14 13:06 UTC
### Bug summary

`check(POST_NOTIFICATIONS)` doesn't return `blocked` status 

when permission not requestable anymore :(

### Library version

3.6.1

### Environment info

```shell
System:
    OS: Linux 5.4 Linux Mint 20.2 (Uma)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 7.83 GB / 15.46 GB
    Shell: 3.5.1 - /usr/bin/fish
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.1.2 - /usr/bin/npm
    Watchman: 20211205.130157.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.17 - /usr/lib/jvm/default-java/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 16.13.1 
    react-native: 0.70.6 => 0.70.6 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

```tsx
// 1st attempt: Dialog Appear (user press deny)
check(POST_NOTIFICATIONS)    // denied
request(POST_NOTIFICATIONS)  // denied

// 2nd attempt: Dialog Appear (user press deny)
check(POST_NOTIFICATIONS)    // denied
request(POST_NOTIFICATIONS)  // blocked

// 3nd attempt: Dialog DOESN'T Appear !!!
check(POST_NOTIFICATIONS)    // denied ??? Why, expected blocked
request(POST_NOTIFICATIONS)  // blocked
```

### Reproducible sample code

```js
see above...
```

**Comment by zoontek** [comment] 2022-12-14 13:52
@retyui That's actually the Android flow https://github.com/zoontek/react-native-permissions#android-flow

Duplicate of a lot of existing issues (ex https://github.com/zoontek/react-native-permissions/issues/725)

More infos: https://github.com/zoontek/react-native-permissions/issues/714#issuecomment-1238382187

Note that on Android 11+, the "Never ask again" checkbox has been removed, permission are requestable two times. So no issue at all here.

**Closed as completed** 2022-12-14 13:53 UTC
Labels: invalid

**Comment by pierrezimmermannbam** [comment] 2022-12-19 15:45
@zoontek we had a similar issue, the fact that check returns blocked after request returns blocked can lead to think that it will always be the case whereas it is not if the user has refused the permission from the app settings. Do we really want check to return the blocked status in some cases ? I'm not sure it's useful if we can't really rely on it and it seems we're not the only one to have misunderstood the behavior. Imo it would be worth it to detail a bit further this behavior in the read me next to the flow diagram, wdyt ?
