### ISSUE TITLE
when request for ACCESS_BACKGROUND_LOCATION should open a dialogue window instead of taking to settings page

### ISSUE THREAD

**Issue by Yandamuri** [zoontek/react-native-permissions#624] opened 2021-06-29 12:12 UTC
# Feature request

when request for ACCESS_BACKGROUND_LOCATION user is taken to settings page like below

 
![123049216-f2a4ee00-d41c-11eb-91db-39cd4a7e9de4](https://user-images.githubusercontent.com/31983789/123794524-8fc1c400-d900-11eb-855c-54ab8acafda0.png)

Instead, If below dialogue window should be opened.

<img width="277" alt="Screenshot 2021-06-29 at 5 24 58 PM" src="https://user-images.githubusercontent.com/31983789/123794757-d6afb980-d900-11eb-9cda-7802e236382e.png">
 

## Why it is needed

If the user is taken to user, It will be unnecessary navigation and user has to get back to app after granting permission. IF dialogue is opened inside app it self it will save user time.

## Possible implementation

I am unable to think of any possible solutions as I am new to react-native and not aware of any native code.

### Code sample

I do not have any code sample for now.

Please correct me if am asking for is against to nature of permissions system. Thank You.

**Comment by zoontek** [comment] 2021-06-29 12:32
Duplicate of https://github.com/zoontek/react-native-permissions/issues/623

**Closed as completed by zoontek** 2021-06-29 12:32 UTC
