### ISSUE TITLE
RN 0.50.3 compileReleaseJavaWithJavac

### ISSUE THREAD

**Issue by OrangeFlavoredColdCoffee** [zoontek/react-native-permissions#180] opened 2017-11-10 08:18 UTC
i tried  0.2.4、 0.2.7   、1.0.1     same error

**Comment by MoOx** [comment] 2017-11-14 11:08
Duplicate of #181 (or the opposite haha)

**Comment by zoontek** [comment] 2017-11-21 23:12
@OrangeFlavoredColdCoffee Do you use Android Studio? Which version?

**Comment by OrangeFlavoredColdCoffee** [comment] 2017-11-24 08:21
@zoontek  yes ,2.3.0 and now i update to 3.0.1

**Closed as completed** 2017-11-24 08:22 UTC
