### ISSUE TITLE
No permission handler after upgrading from RN 0.64 to 0.68

### ISSUE THREAD

**Issue by JB-CHAUVIN** [zoontek/react-native-permissions#695] opened 2022-06-24 09:29 UTC
### Bug summary

Hello,

I have the following error : "**No permission handler detected**". 
![error694](https://user-images.githubusercontent.com/8957878/175506921-f40150cb-b94e-4c36-a6a9-ef82a2d798e5.jpg)

I followed all steps to clean Derived data, XCODE project, installed Pods correctly, deleted the app... etc...
I really tried everything but it's not working after upgrading from RN 0.64 to 0.68.

Any ideas ?

### Library version

3.3.1

### Environment info

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 28.11 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - /usr/local/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 6.14.16 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/javac
  npmPackages:
    react: 17.0.2
    react-native: 0.68.1
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
N/A
```

**Comment by zoontek** [comment] 2022-06-24 09:32
Duplicate of https://github.com/zoontek/react-native-permissions/issues/694

**Closed as completed** 2022-06-24 09:31 UTC
Labels: duplicate
